/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author 52951
 */
public class MenuTetris extends javax.swing.JFrame {

    /**
     * Creates new form MenuTetris4
     */
    public MenuTetris() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir = new javax.swing.JLabel();
        ajustes = new javax.swing.JLabel();
        comoJugar = new javax.swing.JLabel();
        jugar = new javax.swing.JLabel();
        puntaje = new javax.swing.JLabel();
        tetrisP = new javax.swing.JLabel();
        fondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(399, 639));
        setResizable(false);
        getContentPane().setLayout(null);

        salir.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonTetris.png"))); // NOI18N
        salir.setText("SALIR");
        salir.setDoubleBuffered(true);
        salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(salir);
        salir.setBounds(100, 530, 200, 80);

        ajustes.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        ajustes.setForeground(new java.awt.Color(255, 255, 255));
        ajustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonTetris.png"))); // NOI18N
        ajustes.setText("AJUSTES");
        ajustes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ajustes);
        ajustes.setBounds(100, 420, 200, 80);

        comoJugar.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        comoJugar.setForeground(new java.awt.Color(255, 255, 255));
        comoJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonTetris.png"))); // NOI18N
        comoJugar.setText("COMO JUGAR");
        comoJugar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(comoJugar);
        comoJugar.setBounds(100, 320, 200, 80);
        comoJugar.getAccessibleContext().setAccessibleName("como jugar");

        jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botoncitoTetris.png"))); // NOI18N
        getContentPane().add(jugar);
        jugar.setBounds(100, 120, 200, 80);

        puntaje.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        puntaje.setForeground(new java.awt.Color(255, 255, 255));
        puntaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonTetris.png"))); // NOI18N
        puntaje.setText("PUNTAJE");
        puntaje.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        puntaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(puntaje);
        puntaje.setBounds(100, 220, 200, 80);

        tetrisP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tetrisImage.png"))); // NOI18N
        getContentPane().add(tetrisP);
        tetrisP.setBounds(80, 20, 0, 70);

        fondoMenu.setForeground(new java.awt.Color(255, 255, 255));
        fondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.jpg"))); // NOI18N
        fondoMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fondoMenu.setOpaque(true);
        getContentPane().add(fondoMenu);
        fondoMenu.setBounds(0, 0, 0, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTetris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTetris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTetris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTetris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTetris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ajustes;
    private javax.swing.JLabel comoJugar;
    private javax.swing.JLabel fondoMenu;
    private javax.swing.JLabel jugar;
    private javax.swing.JLabel puntaje;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel tetrisP;
    // End of variables declaration//GEN-END:variables
}
